### ISSUE TITLE
anti thing

### ISSUE THREAD

**Issue by E-enuts** [EvilBytecode/WindKitty-Rat#2]
i runned it by accident to test it my self and my cpu wasn't the same as before

**Comment by E-enuts** [comment]
so if you could do an anti thing that deletes it would be gratefull

**Comment by EvilBytecode** [comment]
sure i would recommend using my repository called "windkitty-protector" it wll remove grabbers. https://github.com/EvilBytecode/WindKitty-Protector

also i would be happy, if you would star the repository or follow me.
