### ISSUE TITLE
yo how do u get a key? like what does <your_key> mean?

### ISSUE THREAD

**Issue by Robloxxian** [EvilBytecode/WindKitty-Rat#3]

**Comment by EvilBytecode** [comment]
follow me, anyways when you run the rat it creates channel with your key.

**Comment by herofahad777** [comment]
but what is the key where can I get it, and I runned the code but not able to get any info of the user

**Comment by EvilBytecode** [comment]
The key is generated when user runs it, the key is different to each client. so it can support multiple connections

**Comment by EvilBytecode** [comment]
thunderkitty is on the way.. soon releasing an golang version that will be op.. stay tuned..
![logo](https://github.com/EvilBytecode/WindKitty-Rat/assets/151552809/a85490e3-9f05-4777-a944-28f6c783b1ee)
