### ISSUE TITLE
Not  work

### ISSUE THREAD

**Issue by monkeyrizz** [EvilBytecode/WindKitty-Rat#4]
whenever i put the bot token and server id it says unable to create proces using C; please help me.

**Comment by EvilBytecode** [comment]
can you show picture!?

**Comment by monkeyrizz** [comment]
<img width="511" alt="image" src="https://github.com/EvilBytecode/WindKitty-Rat/assets/169537777/b85a7634-e88d-4f68-959e-ee8d9a0bbea4">
look

**Comment by monkeyrizz** [comment]
> can you show picture!?

<img width="511" alt="image" src="https://github.com/EvilBytecode/WindKitty-Rat/assets/169537777/12563a41-d28f-4ca6-8446-7bab346f368c">
please help what to do now :(

**Comment by EvilBytecode** [comment]
ok so it says auto_py_to_exe isnt installed how can you fix this? go to cmd and execute this command:
1 : ```    py --version ``` why? so i verify taht you have python installed before doing anything further
2 : ```    pip install auto_py_to_exe ``` this installs the module that youre missing

**Comment by herofahad777** [comment]
I have created the exe file but after launching the file there is no response from the exe and the bot is not online my av is full time disable so it don't cause any problem

**Comment by monkeyrizz** [comment]
> ok so it says auto_py_to_exe isnt installed how can you fix this? go to cmd and execute this command: 1 : ` py --version` why? so i verify taht you have python installed before doing anything further 2 : ` pip install auto_py_to_exe` this installs the module that youre missing

coud u help me on discord so i can screenshare?

**Comment by monkeyrizz** [comment]
> ok so it says auto_py_to_exe isnt installed how can you fix this? go to cmd and execute this command: 1 : ` py --version` why? so i verify taht you have python installed before doing anything further 2 : ` pip install auto_py_to_exe` this installs the module that youre missing

btw i did this

**Comment by EvilBytecode** [comment]
idek, theres tutorial and idek bro.

**Comment by monkeyrizz** [comment]
> idek, theres tutorial and idek bro.

<img width="829" alt="image" src="https://github.com/EvilBytecode/WindKitty-Rat/assets/169537777/e61d009e-bd13-481a-bbd0-bf72d5fcca52">
it says this pls help can i add u on discord?

**Comment by EvilBytecode** [comment]
idek Alexander Kottaras

**Comment by EvilBytecode** [comment]
thunderkitty is on the way.. soon releasing an golang version that will be op.. stay tuned..
![logo](https://github.com/EvilBytecode/WindKitty-Rat/assets/151552809/a85490e3-9f05-4777-a944-28f6c783b1ee)
