### ISSUE TITLE
Python is not installed, Installing it!

### ISSUE THREAD

**Issue by VikiBiki13** [EvilBytecode/WindKitty-Rat#5]
when running installer.bat

curl: option -o: requires parameter
curl: try 'curl --help' for more information
Invalid switch - "/quiet".
The syntax of the command is incorrect.
Press any key to continue . . .    

help?

**Comment by EvilBytecode** [comment]
yup go to : https://github.com/KDot227/PythonPathFixer/blob/main/main.bat download main.bat and run it!

**Comment by EvilBytecode** [comment]
thunderkitty is on the way.. soon releasing an golang version that will be op.. stay tuned..
![logo](https://github.com/EvilBytecode/WindKitty-Rat/assets/151552809/a85490e3-9f05-4777-a944-28f6c783b1ee)
