### ISSUE TITLE
Can you tell what to select in the py to exe windows

### ISSUE THREAD

**Issue by herofahad777** [EvilBytecode/WindKitty-Rat#6]

**Comment by herofahad777** [comment]
Still waiting i put the WindKittyRat.py in the path of autopytoexe but after running it, it doesn't work

**Comment by EvilBytecode** [comment]
ermmm what the sigma

**Comment by EvilBytecode** [comment]
thunderkitty is on the way.. soon releasing an golang version that will be op.. stay tuned..
![logo](https://github.com/EvilBytecode/WindKitty-Rat/assets/151552809/a85490e3-9f05-4777-a944-28f6c783b1ee)
